<svelte:head>
	<title>Style Guide — Haven Design System</title>
</svelte:head>

<div class="mx-auto max-w-7xl px-6 py-12">
	<header class="mb-16">
		<p class="text-xs font-medium uppercase tracking-widest text-surface-muted-fg">Design System</p>
		<h1 class="mt-3 text-4xl">Haven Style Guide</h1>
		<p class="mt-4 max-w-lg text-surface-muted-fg leading-relaxed">
			Brand tokens generated by the design token pipeline from <code class="rounded bg-surface-muted px-1.5 py-0.5 font-mono text-sm">brand.json</code>.
			All values are WCAG AA compliant.
		</p>
	</header>

	<!-- COLOR PALETTE -->
	<section class="mb-16">
		<h2 class="text-2xl">Color Palette</h2>

		<h3 class="mt-8 text-xs font-semibold uppercase tracking-widest text-surface-muted-fg">Brand Colors</h3>
		<div class="mt-4 grid gap-3 sm:grid-cols-3">
			<div class="overflow-hidden rounded-sm border border-surface-border">
				<div class="h-20 bg-primary"></div>
				<div class="p-3">
					<p class="text-sm font-medium">Terracotta</p>
					<p class="font-mono text-xs text-surface-muted-fg">#a3522d · primary</p>
				</div>
			</div>
			<div class="overflow-hidden rounded-sm border border-surface-border">
				<div class="h-20 bg-secondary"></div>
				<div class="p-3">
					<p class="text-sm font-medium">Terracotta Deep</p>
					<p class="font-mono text-xs text-surface-muted-fg">#8a4425 · secondary</p>
				</div>
			</div>
			<div class="overflow-hidden rounded-sm border border-surface-border">
				<div class="h-20 bg-accent"></div>
				<div class="p-3">
					<p class="text-sm font-medium">Eucalyptus</p>
					<p class="font-mono text-xs text-surface-muted-fg">#2c6e63 · accent</p>
				</div>
			</div>
		</div>

		<h3 class="mt-10 text-xs font-semibold uppercase tracking-widest text-surface-muted-fg">Semantic Colors</h3>
		<div class="mt-4 grid gap-3 sm:grid-cols-4">
			<div class="overflow-hidden rounded-sm border border-surface-border">
				<div class="h-14 bg-success"></div>
				<div class="p-3">
					<p class="text-sm font-medium">In Stock</p>
					<p class="font-mono text-xs text-surface-muted-fg">#2c6e63</p>
				</div>
			</div>
			<div class="overflow-hidden rounded-sm border border-surface-border">
				<div class="h-14 bg-warning"></div>
				<div class="p-3">
					<p class="text-sm font-medium">Low Stock</p>
					<p class="font-mono text-xs text-surface-muted-fg">#996d1a</p>
				</div>
			</div>
			<div class="overflow-hidden rounded-sm border border-surface-border">
				<div class="h-14 bg-error"></div>
				<div class="p-3">
					<p class="text-sm font-medium">Unavailable</p>
					<p class="font-mono text-xs text-surface-muted-fg">#b5403a</p>
				</div>
			</div>
			<div class="overflow-hidden rounded-sm border border-surface-border">
				<div class="h-14 bg-info"></div>
				<div class="p-3">
					<p class="text-sm font-medium">Info</p>
					<p class="font-mono text-xs text-surface-muted-fg">#4a7fa5</p>
				</div>
			</div>
		</div>

		<h3 class="mt-10 text-xs font-semibold uppercase tracking-widest text-surface-muted-fg">Neutral Scale</h3>
		<div class="mt-4 flex overflow-hidden rounded-sm border border-surface-border">
			{#each neutrals as n}
				<div class="flex-1" style="background-color: {n.hex}; min-height: 64px;" title="{n.label}: {n.hex}"></div>
			{/each}
		</div>
		<div class="mt-2 flex">
			{#each neutrals as n}
				<div class="flex-1 text-center">
					<p class="font-mono text-[0.625rem] text-surface-muted-fg">{n.label}</p>
				</div>
			{/each}
		</div>

		<h3 class="mt-10 text-xs font-semibold uppercase tracking-widest text-surface-muted-fg">Surfaces</h3>
		<div class="mt-4 grid gap-3 sm:grid-cols-3">
			<div class="rounded-sm border border-surface-border bg-surface-bg p-6">
				<p class="text-sm font-medium">Background</p>
				<p class="font-mono text-xs text-surface-muted-fg">#faf9f7</p>
			</div>
			<div class="rounded-sm border border-surface-border bg-surface-card p-6">
				<p class="text-sm font-medium text-surface-card-fg">Card</p>
				<p class="font-mono text-xs text-surface-muted-fg">#ffffff</p>
			</div>
			<div class="rounded-sm bg-surface-muted p-6">
				<p class="text-sm font-medium">Muted</p>
				<p class="font-mono text-xs text-surface-muted-fg">#f5f3f0</p>
			</div>
		</div>
	</section>

	<!-- TYPOGRAPHY -->
	<section class="mb-16">
		<h2 class="text-2xl">Typography</h2>

		<div class="mt-8 grid gap-8 lg:grid-cols-2">
			<!-- Display font -->
			<div class="rounded-sm border border-surface-border p-6">
				<p class="text-xs font-medium uppercase tracking-widest text-surface-muted-fg">Display — DM Serif Display</p>
				<p class="mt-4 font-display text-4xl">The quick brown fox</p>
				<p class="mt-2 font-display text-2xl">jumps over the lazy dog</p>
				<p class="mt-4 text-xs text-surface-muted-fg">Used for: h1, h2, h3, product names in editorial layouts, category headers</p>
			</div>

			<!-- Body font -->
			<div class="rounded-sm border border-surface-border p-6">
				<p class="text-xs font-medium uppercase tracking-widest text-surface-muted-fg">Body — DM Sans</p>
				<p class="mt-4 text-lg">The quick brown fox jumps over the lazy dog</p>
				<p class="mt-2 text-sm">ABCDEFGHIJKLMNOPQRSTUVWXYZ abcdefghijklmnopqrstuvwxyz 0123456789</p>
				<p class="mt-4 text-xs text-surface-muted-fg">Used for: body text, navigation, buttons, labels, descriptions</p>
			</div>
		</div>

		<h3 class="mt-10 text-xs font-semibold uppercase tracking-widest text-surface-muted-fg">Type Scale</h3>
		<div class="mt-6 space-y-6 border-t border-surface-border pt-6">
			<div class="flex items-baseline gap-6">
				<span class="w-24 shrink-0 font-mono text-xs text-surface-muted-fg">hero / 3.5rem</span>
				<span class="font-display text-[3.5rem] leading-[1.05]">Haven</span>
			</div>
			<div class="flex items-baseline gap-6">
				<span class="w-24 shrink-0 font-mono text-xs text-surface-muted-fg">h2 / 2.25rem</span>
				<span class="font-display text-[2.25rem] leading-[1.15]">Shop by Room</span>
			</div>
			<div class="flex items-baseline gap-6">
				<span class="w-24 shrink-0 font-mono text-xs text-surface-muted-fg">h3 / 1.5rem</span>
				<span class="font-display text-[1.5rem] leading-[1.25]">Modern Leather Sectional</span>
			</div>
			<div class="flex items-baseline gap-6">
				<span class="w-24 shrink-0 font-mono text-xs text-surface-muted-fg">h4 / 1.125rem</span>
				<span class="text-[1.125rem] font-semibold leading-[1.35]">Free shipping over $500</span>
			</div>
			<div class="flex items-baseline gap-6">
				<span class="w-24 shrink-0 font-mono text-xs text-surface-muted-fg">body-lg</span>
				<span class="text-[1.125rem] leading-[1.65]">Pieces that hold up to real life. Pet-friendly fabrics, washable covers.</span>
			</div>
			<div class="flex items-baseline gap-6">
				<span class="w-24 shrink-0 font-mono text-xs text-surface-muted-fg">body</span>
				<span class="text-base leading-[1.6]">Solid walnut with a waterfall edge and matte lacquer finish.</span>
			</div>
			<div class="flex items-baseline gap-6">
				<span class="w-24 shrink-0 font-mono text-xs text-surface-muted-fg">body-sm</span>
				<span class="text-sm leading-[1.5]">Top-grain leather · Seats 5 · 112" x 85"</span>
			</div>
			<div class="flex items-baseline gap-6">
				<span class="w-24 shrink-0 font-mono text-xs text-surface-muted-fg">label</span>
				<span class="text-xs font-medium uppercase tracking-widest">Featured · In Stock · Sale</span>
			</div>
			<div class="flex items-baseline gap-6">
				<span class="w-24 shrink-0 font-mono text-xs text-surface-muted-fg">code</span>
				<span class="font-mono text-[0.8125rem]">brand-forge export css --kit brand.json</span>
			</div>
		</div>
	</section>

	<!-- COMPONENTS -->
	<section class="mb-16">
		<h2 class="text-2xl">Components</h2>

		<!-- Buttons -->
		<h3 class="mt-8 text-xs font-semibold uppercase tracking-widest text-surface-muted-fg">Buttons</h3>
		<div class="mt-4 flex flex-wrap items-center gap-4">
			<button class="rounded-sm bg-surface-fg px-6 py-3 text-sm font-medium text-surface-bg transition-opacity hover:opacity-85">
				Primary CTA
			</button>
			<button class="rounded-sm border border-surface-fg px-6 py-3 text-sm font-medium text-surface-fg transition-colors hover:bg-surface-fg hover:text-surface-bg">
				Secondary
			</button>
			<button class="rounded-sm bg-primary px-6 py-3 text-sm font-medium text-white transition-colors hover:bg-secondary">
				Accent
			</button>
			<button class="rounded-sm border border-surface-border px-6 py-3 text-sm font-medium text-surface-muted-fg transition-colors hover:border-neutral-400 hover:text-surface-fg">
				Tertiary
			</button>
		</div>
		<p class="mt-3 text-xs text-surface-muted-fg">Primary CTA uses fg/bg inversion (dark on light). Accent (terracotta) used for emphasis. Tertiary for filters and secondary actions.</p>

		<!-- Badges -->
		<h3 class="mt-10 text-xs font-semibold uppercase tracking-widest text-surface-muted-fg">Badges</h3>
		<div class="mt-4 flex flex-wrap items-center gap-3">
			<span class="rounded-sm bg-success/10 px-2.5 py-1 text-xs font-medium text-success">In Stock</span>
			<span class="rounded-sm bg-warning/10 px-2.5 py-1 text-xs font-medium text-warning">Low Stock</span>
			<span class="rounded-sm bg-error/10 px-2.5 py-1 text-xs font-medium text-error">Out of Stock</span>
			<span class="rounded-sm bg-primary/10 px-2.5 py-1 text-xs font-medium text-primary">Sale</span>
			<span class="rounded-sm bg-info/10 px-2.5 py-1 text-xs font-medium text-info">Trending</span>
			<span class="rounded-sm bg-surface-muted px-2.5 py-1 text-xs font-medium text-surface-muted-fg">leather</span>
			<span class="rounded-sm bg-surface-muted px-2.5 py-1 text-xs font-medium text-surface-muted-fg">modern</span>
		</div>

		<!-- Cards -->
		<h3 class="mt-10 text-xs font-semibold uppercase tracking-widest text-surface-muted-fg">Product Cards</h3>
		<div class="mt-4 grid gap-6 sm:grid-cols-3">
			<!-- Editorial card (Gatherer) -->
			<div class="overflow-hidden rounded-sm border border-surface-border">
				<div class="aspect-[4/3] bg-surface-muted"></div>
				<div class="p-4">
					<h4 class="font-display text-lg">Modern Leather Sectional</h4>
					<p class="mt-1 text-sm text-surface-muted-fg">Top-grain leather with reversible chaise</p>
					<p class="mt-3 font-medium">$2,499</p>
				</div>
			</div>

			<!-- Compact card (Hunter) -->
			<div class="overflow-hidden rounded-sm border border-surface-border">
				<div class="aspect-square bg-surface-muted"></div>
				<div class="p-3">
					<h4 class="text-sm font-medium">Compact Student Desk</h4>
					<p class="mt-0.5 text-xs text-surface-muted-fg">48" x 24" · Engineered wood</p>
					<p class="mt-2 text-base font-semibold">$129</p>
					<button class="mt-2 w-full rounded-sm bg-surface-fg py-2 text-xs font-medium text-surface-bg">Add to Cart</button>
				</div>
			</div>

			<!-- Sale card -->
			<div class="overflow-hidden rounded-sm border border-surface-border">
				<div class="relative aspect-[4/3] bg-surface-muted">
					<span class="absolute left-3 top-3 rounded-sm bg-primary/10 px-2 py-0.5 text-xs font-medium text-primary">Sale</span>
				</div>
				<div class="p-4">
					<h4 class="font-display text-lg">Velvet Lounge Sofa</h4>
					<p class="mt-1 text-sm text-surface-muted-fg">Performance velvet, 3-seat</p>
					<div class="mt-3 flex items-baseline gap-2">
						<span class="font-medium text-primary">$1,599</span>
						<span class="text-sm text-surface-muted-fg line-through">$1,899</span>
					</div>
				</div>
			</div>
		</div>
		<p class="mt-3 text-xs text-surface-muted-fg">Left: Gatherer editorial card (4:3 ratio, serif heading, description). Center: Hunter compact card (square, quick-add). Right: Sale treatment.</p>

		<!-- Form elements -->
		<h3 class="mt-10 text-xs font-semibold uppercase tracking-widest text-surface-muted-fg">Form Elements</h3>
		<div class="mt-4 flex flex-wrap items-end gap-4">
			<div>
				<label class="text-xs font-medium text-surface-muted-fg">Text Input</label>
				<input type="text" placeholder="Search..." class="mt-1 block rounded-sm border border-surface-border bg-surface-card px-3 py-2 text-sm placeholder:text-surface-muted-fg focus:border-primary focus:outline-none focus:ring-1 focus:ring-primary" />
			</div>
			<div>
				<label class="text-xs font-medium text-surface-muted-fg">Select</label>
				<select class="mt-1 block rounded-sm border border-surface-border bg-surface-card px-3 py-2 text-sm focus:border-primary focus:outline-none focus:ring-1 focus:ring-primary">
					<option>Price: Low to High</option>
					<option>Price: High to Low</option>
				</select>
			</div>
		</div>
	</section>

	<!-- SPACING & RADIUS -->
	<section class="mb-16">
		<h2 class="text-2xl">Spacing & Radius</h2>

		<h3 class="mt-8 text-xs font-semibold uppercase tracking-widest text-surface-muted-fg">Border Radius</h3>
		<div class="mt-4 flex flex-wrap items-end gap-4">
			{#each radii as r}
				<div class="text-center">
					<div class="h-16 w-16 border border-surface-border bg-surface-muted" style="border-radius: {r.value};"></div>
					<p class="mt-2 font-mono text-[0.625rem] text-surface-muted-fg">{r.label}</p>
				</div>
			{/each}
		</div>
		<p class="mt-3 text-xs text-surface-muted-fg">Haven uses minimal radius (0-6px). Rounded-sm (2px) for most elements. No pill shapes except full-round badges.</p>
	</section>

	<!-- VOICE -->
	<section class="mb-16">
		<h2 class="text-2xl">Voice & Tone</h2>

		<div class="mt-8 grid gap-6 sm:grid-cols-2">
			<div class="rounded-sm border border-surface-border p-6">
				<h3 class="text-xs font-semibold uppercase tracking-widest text-accent">Do</h3>
				<p class="mt-4 leading-relaxed">
					Solid walnut with a waterfall edge and matte lacquer finish. Sized for smaller living rooms — 48 inches won't overwhelm the space.
				</p>
			</div>
			<div class="rounded-sm border border-surface-border p-6">
				<h3 class="text-xs font-semibold uppercase tracking-widest text-error">Don't</h3>
				<p class="mt-4 leading-relaxed">
					This stunning, best-in-class coffee table features a thoughtfully designed silhouette crafted from premium materials to elevate any living space.
				</p>
			</div>
		</div>

		<div class="mt-6 grid gap-6 sm:grid-cols-2">
			<div class="rounded-sm border border-surface-border p-6">
				<h3 class="text-xs font-semibold uppercase tracking-widest text-accent">Do</h3>
				<p class="mt-4 leading-relaxed">
					Sofas built to hold up to real life. Pet-friendly fabrics, washable covers, frames that don't creak at year five.
				</p>
			</div>
			<div class="rounded-sm border border-surface-border p-6">
				<h3 class="text-xs font-semibold uppercase tracking-widest text-error">Don't</h3>
				<p class="mt-4 leading-relaxed">
					Discover our curated collection of world-class sofas, each thoughtfully designed to transform your living room into a sanctuary of style.
				</p>
			</div>
		</div>

		<h3 class="mt-10 text-xs font-semibold uppercase tracking-widest text-surface-muted-fg">Voice Attributes</h3>
		<div class="mt-4 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">
			{#each voiceAttributes as attr}
				<div class="rounded-sm border border-surface-border p-4">
					<p class="font-medium">{attr.trait}</p>
					<p class="mt-2 text-sm text-surface-muted-fg">{attr.description}</p>
				</div>
			{/each}
		</div>
	</section>

	<!-- DEV MODE -->
	<section class="mb-16">
		<h2 class="text-2xl">Dev Mode Overlay</h2>
		<p class="mt-4 text-surface-muted-fg">Add <code class="rounded bg-surface-muted px-1.5 py-0.5 font-mono text-sm">?dev=true</code> to any URL to see the persona detection overlay.</p>

		<div class="mt-6 rounded-sm border border-accent/30 bg-accent/5 p-4">
			<div class="flex items-center justify-between">
				<div>
					<p class="text-xs font-medium uppercase tracking-wider text-accent">Dev Mode</p>
					<p class="mt-1 text-sm text-surface-muted-fg">
						Detected: <span class="font-semibold text-surface-fg">gatherer</span> (80% confidence)
					</p>
				</div>
				<div class="flex gap-2">
					<button class="rounded-sm bg-primary px-3 py-1.5 text-xs font-medium text-white">Gatherer</button>
					<button class="rounded-sm border border-surface-border px-3 py-1.5 text-xs font-medium text-surface-muted-fg">Hunter</button>
				</div>
			</div>
		</div>
		<p class="mt-3 text-xs text-surface-muted-fg">Uses accent (eucalyptus) for dev mode chrome to visually separate from commerce UI.</p>
	</section>
</div>

<script lang="ts">
	const neutrals = [
		{ label: '50', hex: '#faf9f7' },
		{ label: '100', hex: '#f5f3f0' },
		{ label: '200', hex: '#ebe8e3' },
		{ label: '300', hex: '#d9d4cc' },
		{ label: '400', hex: '#b5ada2' },
		{ label: '500', hex: '#8c8479' },
		{ label: '600', hex: '#6b6459' },
		{ label: '700', hex: '#4d473e' },
		{ label: '800', hex: '#353129' },
		{ label: '900', hex: '#231f1a' },
		{ label: '950', hex: '#141210' },
	];

	const radii = [
		{ label: 'none', value: '0' },
		{ label: 'sm', value: '2px' },
		{ label: 'md', value: '4px' },
		{ label: 'lg', value: '6px' },
		{ label: 'xl', value: '8px' },
		{ label: '2xl', value: '12px' },
		{ label: 'full', value: '9999px' },
	];

	const voiceAttributes = [
		{ trait: 'Warm', description: 'Conversational, like a knowledgeable friend — not a salesperson, not a robot.' },
		{ trait: 'Confident', description: 'Declarative, specific, backed by product knowledge. No hedging.' },
		{ trait: 'Editorial', description: 'Reads like a shelter magazine, not a product catalog. Story over specs.' },
		{ trait: 'Unhurried', description: 'No pressure. Furniture is a considered purchase. Give space to decide.' },
	];
</script>
