/**
 * Ember brand — outdoor fire & cooking products.
 * 18 products across 4 categories.
 */

export const emberCategories = [
	{ name: 'Ember Fire Pits' },
	{ name: 'Ember Camp Stoves' },
	{ name: 'Ember Grills' },
	{ name: 'Ember Accessories' },
];

export const emberProducts = [
	// ─── Fire Pits ────────────────────────────────────────────────
	{
		name: 'Bonfire Smokeless Fire Pit',
		type: 'physical' as const,
		price: 349.99,
		weight: 20,
		description: 'Double-wall stainless steel smokeless fire pit. 19.5-inch diameter fits six chairs around it. Secondary combustion burns off smoke before it reaches your eyes. Burns standard firewood. No assembly, no gas lines, no excuses.',
		categories: ['Ember Fire Pits'],
		custom_fields: [
			{ name: 'Material', value: '304 stainless steel, double-wall' },
			{ name: 'Diameter', value: '19.5 inches' },
			{ name: 'Weight', value: '20 lbs' },
			{ name: 'Fuel', value: 'Firewood' },
			{ name: 'Smokeless', value: 'Yes, secondary combustion' },
		],
		image_url: 'https://images.unsplash.com/photo-1597243777052-5c325d821f35?w=800',
	},
	{
		name: 'Yukon XL Fire Pit',
		type: 'physical' as const,
		price: 599.99,
		weight: 38,
		description: 'Full-size 27-inch smokeless fire pit for large gatherings. Corten steel exterior develops a natural rust patina over time — it gets more beautiful with age. Handles 18-inch logs. The centerpiece of the backyard.',
		categories: ['Ember Fire Pits'],
		custom_fields: [
			{ name: 'Material', value: 'Corten steel exterior, stainless interior' },
			{ name: 'Diameter', value: '27 inches' },
			{ name: 'Weight', value: '38 lbs' },
			{ name: 'Log Size', value: 'Up to 18 inches' },
			{ name: 'Patina', value: 'Develops naturally over time' },
		],
		image_url: 'https://images.unsplash.com/photo-1567449790-26e5e4a53ebb?w=800',
	},
	{
		name: 'Mesa Tabletop Fire',
		type: 'physical' as const,
		price: 109.99,
		weight: 4,
		description: 'Compact tabletop fire bowl powered by isopropyl alcohol. No smoke, no soot, works indoors or out. Stainless steel construction with a tempered glass wind guard. Burns for 30-45 minutes per fill. The dinner party conversation starter.',
		categories: ['Ember Fire Pits'],
		custom_fields: [
			{ name: 'Fuel', value: 'Isopropyl alcohol' },
			{ name: 'Burn Time', value: '30-45 minutes per fill' },
			{ name: 'Indoor/Outdoor', value: 'Both' },
			{ name: 'Material', value: 'Stainless steel + tempered glass' },
			{ name: 'Weight', value: '4 lbs' },
		],
		image_url: 'https://images.unsplash.com/photo-1602425121688-4e8c3b4a3b0f?w=800',
	},
	{
		name: 'Ranger Portable Fire Pit',
		type: 'physical' as const,
		price: 229.99,
		weight: 15,
		description: 'Compact 15-inch smokeless fire pit that fits in a car trunk. Comes with a carrying case and stand. Full secondary combustion airflow in a travel-friendly package. For campsites, beaches, and tailgates.',
		categories: ['Ember Fire Pits'],
		custom_fields: [
			{ name: 'Diameter', value: '15 inches' },
			{ name: 'Weight', value: '15 lbs' },
			{ name: 'Portable', value: 'Yes, with carrying case' },
			{ name: 'Smokeless', value: 'Yes, secondary combustion' },
			{ name: 'Material', value: '304 stainless steel' },
		],
		image_url: 'https://images.unsplash.com/photo-1510672981848-a1c4f1cb5ccf?w=800',
	},
	{
		name: 'Propane Fire Table',
		type: 'physical' as const,
		price: 799.99,
		weight: 60,
		description: 'Rectangular propane fire table with lava rock bed and adjustable flame. 55,000 BTU output heats a 10-foot radius. Powder-coated aluminum frame never rusts. Hides a standard 20lb propane tank inside. Ignites with a push button.',
		categories: ['Ember Fire Pits'],
		custom_fields: [
			{ name: 'BTU', value: '55,000' },
			{ name: 'Fuel', value: 'Propane (20lb tank, hidden)' },
			{ name: 'Material', value: 'Powder-coated aluminum' },
			{ name: 'Dimensions', value: '44" x 32" x 24"' },
			{ name: 'Ignition', value: 'Push-button electronic' },
		],
		image_url: 'https://images.unsplash.com/photo-1571757767119-68b8dbed8c97?w=800',
	},

	// ─── Camp Stoves ──────────────────────────────────────────────
	{
		name: 'Lite Backpacking Stove',
		type: 'physical' as const,
		price: 69.99,
		weight: 0.5,
		description: 'Ultralight double-wall wood-burning stove for backpackers. Weighs 9oz and packs flat. Uses twigs and small sticks — no fuel canisters to carry. Generates enough heat to boil a liter of water in 4 minutes.',
		categories: ['Ember Camp Stoves'],
		custom_fields: [
			{ name: 'Weight', value: '9 oz (255g)' },
			{ name: 'Fuel', value: 'Wood (twigs, sticks)' },
			{ name: 'Boil Time', value: '4 min per liter' },
			{ name: 'Packed Size', value: '5" x 5" flat' },
			{ name: 'Material', value: 'Titanium' },
		],
		image_url: 'https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?w=800',
	},
	{
		name: 'Basecamp Dual-Burner',
		type: 'physical' as const,
		price: 179.99,
		weight: 5,
		description: 'Two-burner propane camp stove with 20,000 BTU per burner. Wind-blocking side panels, push-button ignition, and a built-in drip tray. Runs off standard 1lb cylinders or adapts to a 20lb tank. Car camping essential.',
		categories: ['Ember Camp Stoves'],
		custom_fields: [
			{ name: 'Burners', value: '2 x 20,000 BTU' },
			{ name: 'Fuel', value: 'Propane (1lb or 20lb adapter)' },
			{ name: 'Ignition', value: 'Push-button piezo' },
			{ name: 'Weight', value: '12 lbs' },
			{ name: 'Cooking Surface', value: '24" x 14"' },
		],
		image_url: 'https://images.unsplash.com/photo-1504280390367-361c6d9f38f4?w=800',
	},
	{
		name: 'Rocket Stove',
		type: 'physical' as const,
		price: 129.99,
		weight: 8,
		description: 'L-shaped rocket stove that channels heat upward with maximum efficiency. Burns small sticks to produce intense, focused heat. Cast iron construction lasts decades. Great for off-grid cooking, emergency prep, or backyard experiments.',
		categories: ['Ember Camp Stoves'],
		custom_fields: [
			{ name: 'Material', value: 'Cast iron, 6mm thick' },
			{ name: 'Fuel', value: 'Wood sticks, biomass' },
			{ name: 'Efficiency', value: 'Rocket draft design' },
			{ name: 'Weight', value: '18 lbs' },
			{ name: 'Use Case', value: 'Cooking, emergency prep' },
		],
		image_url: 'https://images.unsplash.com/photo-1532978379173-523e16f371f2?w=800',
	},

	// ─── Grills ───────────────────────────────────────────────────
	{
		name: 'Pi Pizza Oven',
		type: 'physical' as const,
		price: 449.99,
		weight: 25,
		description: 'Outdoor pizza oven that hits 950°F in 15 minutes. Bakes Neapolitan-style pizza in 90 seconds. Dual fuel: gas for convenience or wood pellets for flavor. Foldable legs, fits in a car. The backyard upgrade nobody regrets.',
		categories: ['Ember Grills'],
		custom_fields: [
			{ name: 'Max Temp', value: '950°F' },
			{ name: 'Cook Time', value: '60-90 seconds per pizza' },
			{ name: 'Fuel', value: 'Propane or wood pellets' },
			{ name: 'Pizza Size', value: 'Up to 12 inches' },
			{ name: 'Portable', value: 'Yes, folding legs' },
		],
		image_url: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?w=800',
	},
	{
		name: 'Flatrock Griddle',
		type: 'physical' as const,
		price: 349.99,
		weight: 45,
		description: 'Propane-powered flat-top griddle with 640 sq inches of cooking surface. Three independent heat zones for eggs, bacon, and pancakes simultaneously. Heavy-gauge steel top seasons like cast iron. Grease management system keeps cleanup fast.',
		categories: ['Ember Grills'],
		custom_fields: [
			{ name: 'Surface', value: '640 sq inches' },
			{ name: 'Heat Zones', value: '3 independent' },
			{ name: 'BTU', value: '45,000 total' },
			{ name: 'Material', value: 'Heavy-gauge carbon steel' },
			{ name: 'Fuel', value: 'Propane' },
		],
		image_url: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1?w=800',
	},
	{
		name: 'Grill & Smoker Combo',
		type: 'physical' as const,
		price: 699.99,
		weight: 65,
		description: 'Pellet grill and smoker with WiFi temperature control. 800 sq inch cooking area, 180°F to 500°F range. Set it from your phone, monitor with the app, get alerts when dinner is done. Uses standard hardwood pellets.',
		categories: ['Ember Grills'],
		custom_fields: [
			{ name: 'Cooking Area', value: '800 sq inches' },
			{ name: 'Temp Range', value: '180°F - 500°F' },
			{ name: 'Control', value: 'WiFi + app' },
			{ name: 'Fuel', value: 'Hardwood pellets' },
			{ name: 'Hopper', value: '24 lb capacity' },
		],
		image_url: 'https://images.unsplash.com/photo-1529262363583-3c37e40c2b2d?w=800',
	},
	{
		name: 'Portable Charcoal Grill',
		type: 'physical' as const,
		price: 89.99,
		weight: 8,
		description: 'Compact charcoal kettle grill that fits in a backpack bag. 14-inch cooking grate, adjustable air vents for temperature control. Folds down to 4 inches thick. For tailgates, parks, and apartment balconies.',
		categories: ['Ember Grills'],
		custom_fields: [
			{ name: 'Grate Size', value: '14 inches' },
			{ name: 'Fuel', value: 'Charcoal' },
			{ name: 'Packed Size', value: '14" x 14" x 4"' },
			{ name: 'Weight', value: '8 lbs' },
			{ name: 'Temp Control', value: 'Adjustable air vents' },
		],
		image_url: 'https://images.unsplash.com/photo-1558030006-450675393462?w=800',
	},

	// ─── Accessories ──────────────────────────────────────────────
	{
		name: 'Shield Fire Pit Cover',
		type: 'physical' as const,
		price: 49.99,
		weight: 1,
		description: 'Weather-resistant cover for 19-inch fire pits. 600D polyester with PVC backing, UV-treated. Elastic drawstring bottom for a snug fit. Keeps rain, leaves, and debris out between fires.',
		categories: ['Ember Accessories'],
		custom_fields: [
			{ name: 'Fits', value: '19-19.5 inch fire pits' },
			{ name: 'Material', value: '600D polyester, PVC-backed' },
			{ name: 'UV Protection', value: 'Yes' },
			{ name: 'Closure', value: 'Elastic drawstring' },
		],
		image_url: 'https://images.unsplash.com/photo-1600585152220-90363fe7e115?w=800',
	},
	{
		name: 'Cast Iron Cook Top',
		type: 'physical' as const,
		price: 79.99,
		weight: 6,
		description: 'Cast iron cooking grate that sits on top of any 19-inch fire pit. Turns your fire pit into a grill. Pre-seasoned and ready to cook. Removable center for direct flame access. Doubles as a heat diffuser.',
		categories: ['Ember Accessories'],
		custom_fields: [
			{ name: 'Fits', value: '19-19.5 inch fire pits' },
			{ name: 'Material', value: 'Cast iron, pre-seasoned' },
			{ name: 'Weight', value: '14 lbs' },
			{ name: 'Center', value: 'Removable for direct flame' },
		],
		image_url: 'https://images.unsplash.com/photo-1530027644375-9c83053d392e?w=800',
	},
	{
		name: 'Fire Starter Pucks (24-pack)',
		type: 'physical' as const,
		price: 14.99,
		weight: 0.5,
		description: 'All-natural fire starters made from compressed wood shavings and wax. Each puck burns for 10 minutes — enough to light any campfire or fire pit. No lighter fluid taste, no chemical smell. Waterproof packaging for camp kits.',
		categories: ['Ember Accessories'],
		custom_fields: [
			{ name: 'Count', value: '24 pucks' },
			{ name: 'Burn Time', value: '10 min each' },
			{ name: 'Material', value: 'Wood shavings + natural wax' },
			{ name: 'Waterproof', value: 'Packaging is waterproof' },
		],
		image_url: 'https://images.unsplash.com/photo-1487958449943-2429e8be8625?w=800',
	},
	{
		name: 'Firewood Rack with Cover',
		type: 'physical' as const,
		price: 129.99,
		weight: 12,
		description: 'Heavy-duty steel firewood rack with weather cover. Holds a half-cord of firewood. Elevated base keeps wood off wet ground. Includes kindling shelf for small pieces and fire starters. Powder-coated for rust resistance.',
		categories: ['Ember Accessories'],
		custom_fields: [
			{ name: 'Capacity', value: 'Half-cord (4ft x 4ft x 2ft)' },
			{ name: 'Material', value: 'Steel, powder-coated' },
			{ name: 'Cover', value: 'Included, all-weather' },
			{ name: 'Kindling Shelf', value: 'Yes' },
			{ name: 'Assembly', value: '10 minutes, no tools' },
		],
		image_url: 'https://images.unsplash.com/photo-1543076499-a6133cb932fd?w=800',
	},
];
