/**
 * Volt brand — consumer audio products.
 * 20 products across 4 categories.
 */

export const voltCategories = [
	{ name: 'Volt Headphones' },
	{ name: 'Volt Earbuds' },
	{ name: 'Volt Speakers' },
	{ name: 'Volt Gaming' },
];

export const voltProducts = [
	// ─── Headphones ───────────────────────────────────────────────
	{
		name: 'Apex Pro ANC Headphones',
		type: 'physical' as const,
		price: 249.99,
		weight: 0.6,
		description: 'Over-ear active noise cancelling headphones with 40mm custom drivers, adaptive ANC, and 35-hour battery life. USB-C fast charging gives 5 hours in 10 minutes. LDAC and aptX Adaptive codec support for lossless wireless audio.',
		categories: ['Volt Headphones'],
		custom_fields: [
			{ name: 'Driver Size', value: '40mm custom dynamic' },
			{ name: 'Battery Life', value: '35 hours (ANC on)' },
			{ name: 'Codecs', value: 'LDAC, aptX Adaptive, AAC, SBC' },
			{ name: 'Weight', value: '250g' },
			{ name: 'Connectivity', value: 'Bluetooth 5.3, 3.5mm, USB-C' },
		],
		image_url: 'https://images.unsplash.com/photo-1546435770-a3e426bf472b?w=800',
	},
	{
		name: 'Studio Monitor M50',
		type: 'physical' as const,
		price: 179.99,
		weight: 0.55,
		description: 'Reference-grade closed-back studio monitors with flat frequency response for mixing and mastering. 45mm beryllium-coated drivers deliver accurate, uncolored sound. Detachable cables with both coiled and straight options included.',
		categories: ['Volt Headphones'],
		custom_fields: [
			{ name: 'Driver Size', value: '45mm beryllium-coated' },
			{ name: 'Frequency Response', value: '15Hz - 28kHz' },
			{ name: 'Impedance', value: '38 ohms' },
			{ name: 'Weight', value: '285g' },
			{ name: 'Cable', value: 'Detachable, 1.2m straight + 3m coiled' },
		],
		image_url: 'https://images.unsplash.com/photo-1558089687-f282ffcbc126?w=800',
	},
	{
		name: 'Commuter Fold',
		type: 'physical' as const,
		price: 129.99,
		sale_price: 99.99,
		weight: 0.4,
		description: 'Lightweight on-ear Bluetooth headphones that fold flat for commuting. 28-hour battery, multipoint connection to two devices simultaneously, and ambient awareness mode for announcements and traffic.',
		categories: ['Volt Headphones'],
		custom_fields: [
			{ name: 'Driver Size', value: '32mm' },
			{ name: 'Battery Life', value: '28 hours' },
			{ name: 'Weight', value: '175g' },
			{ name: 'Folding', value: 'Yes, flat-fold design' },
			{ name: 'Multipoint', value: '2 devices simultaneously' },
		],
		image_url: 'https://images.unsplash.com/photo-1484704849700-f032a568e944?w=800',
	},
	{
		name: 'Aura Wireless Open-Ear',
		type: 'physical' as const,
		price: 159.99,
		weight: 0.35,
		description: 'Open-ear bone conduction headphones for runners and cyclists. Hear music and your surroundings simultaneously. IP67 waterproof, titanium frame, 8 hours of playback. Built-in MP3 player with 32GB storage for phone-free runs.',
		categories: ['Volt Headphones'],
		custom_fields: [
			{ name: 'Type', value: 'Bone conduction, open-ear' },
			{ name: 'Battery Life', value: '8 hours' },
			{ name: 'Water Resistance', value: 'IP67' },
			{ name: 'Storage', value: '32GB built-in MP3' },
			{ name: 'Weight', value: '29g' },
		],
		image_url: 'https://images.unsplash.com/photo-1608156639585-b3a776571bff?w=800',
	},
	{
		name: 'Kids Safe Headphones',
		type: 'physical' as const,
		price: 39.99,
		weight: 0.3,
		description: 'Volume-limited wireless headphones for kids aged 3-12. Hard-capped at 85dB to protect developing hearing. 24-hour battery, durable flexible headband, and a built-in mic for virtual classroom use.',
		categories: ['Volt Headphones'],
		custom_fields: [
			{ name: 'Volume Limit', value: '85dB max' },
			{ name: 'Battery Life', value: '24 hours' },
			{ name: 'Age Range', value: '3-12 years' },
			{ name: 'Mic', value: 'Built-in boom mic' },
			{ name: 'Durability', value: 'Flexible headband, drop-tested' },
		],
		image_url: 'https://images.unsplash.com/photo-1613040809024-b4ef7ba99bc3?w=800',
	},

	// ─── Earbuds ──────────────────────────────────────────────────
	{
		name: 'Pulse Pro TWS',
		type: 'physical' as const,
		price: 199.99,
		weight: 0.15,
		description: 'True wireless earbuds with hybrid ANC, spatial audio, and adaptive EQ. 10mm planar magnetic drivers deliver audiophile-grade detail. 8 hours per charge, 32 hours with the wireless charging case. IPX5 sweat resistant.',
		categories: ['Volt Earbuds'],
		custom_fields: [
			{ name: 'Driver', value: '10mm planar magnetic' },
			{ name: 'ANC', value: 'Hybrid adaptive, 6 mics' },
			{ name: 'Battery', value: '8h buds / 32h total' },
			{ name: 'Charging', value: 'USB-C, Qi wireless' },
			{ name: 'Water Resistance', value: 'IPX5' },
		],
		image_url: 'https://images.unsplash.com/photo-1590658165737-15a047b7c0a0?w=800',
	},
	{
		name: 'Flex Sport Earbuds',
		type: 'physical' as const,
		price: 89.99,
		weight: 0.12,
		description: 'Workout earbuds with secure-fit ear hooks and IP68 waterproofing — fully submersible. Bass-forward tuning for high-energy training. 10-hour battery, quick-charge case, and physical button controls that work with sweaty fingers.',
		categories: ['Volt Earbuds'],
		custom_fields: [
			{ name: 'Water Resistance', value: 'IP68 (submersible)' },
			{ name: 'Battery', value: '10h buds / 40h total' },
			{ name: 'Fit', value: 'Silicone ear hooks, 4 tip sizes' },
			{ name: 'Controls', value: 'Physical buttons' },
			{ name: 'Driver', value: '12mm dynamic' },
		],
		image_url: 'https://images.unsplash.com/photo-1593642702749-b7d2a804fbcf?w=800',
	},
	{
		name: 'Micro Buds',
		type: 'physical' as const,
		price: 49.99,
		weight: 0.08,
		description: 'Ultra-compact true wireless earbuds for everyday carry. Barely visible when worn. 6 hours of playback with a pocketable case that adds 18 more. Clean, balanced sound for podcasts, calls, and casual listening.',
		categories: ['Volt Earbuds'],
		custom_fields: [
			{ name: 'Size', value: 'Ultra-compact, 4.5g per bud' },
			{ name: 'Battery', value: '6h buds / 24h total' },
			{ name: 'Mic', value: 'Dual MEMS with AI noise reduction' },
			{ name: 'Bluetooth', value: '5.3 with multipoint' },
			{ name: 'Charging', value: 'USB-C' },
		],
		image_url: 'https://images.unsplash.com/photo-1606220588913-b3aacb4d2f46?w=800',
	},
	{
		name: 'Sleep Buds Ultra',
		type: 'physical' as const,
		price: 129.99,
		weight: 0.06,
		description: 'Designed for sleeping. Ultra-low-profile buds with masking soundscapes, white noise, and alarm features. No music streaming — purpose-built for sleep. 10-hour battery lasts all night. Medical-grade silicone tips.',
		categories: ['Volt Earbuds'],
		custom_fields: [
			{ name: 'Purpose', value: 'Sleep-only, noise masking' },
			{ name: 'Profile', value: '6mm low-profile, side-sleeper safe' },
			{ name: 'Battery', value: '10 hours' },
			{ name: 'Sounds', value: '50+ masking soundscapes' },
			{ name: 'Alarm', value: 'Personal alarm, no phone needed' },
		],
		image_url: 'https://images.unsplash.com/photo-1631176093617-63490a3d785a?w=800',
	},
	{
		name: 'Translate Buds',
		type: 'physical' as const,
		price: 179.99,
		weight: 0.1,
		description: 'Real-time translation earbuds supporting 40 languages. Share one bud with a conversation partner for two-way translation. Also works as premium true wireless earbuds with ANC when not translating.',
		categories: ['Volt Earbuds'],
		custom_fields: [
			{ name: 'Languages', value: '40 languages, real-time' },
			{ name: 'Mode', value: 'Conversation sharing (1 bud each)' },
			{ name: 'ANC', value: 'Hybrid active noise cancellation' },
			{ name: 'Battery', value: '7h buds / 28h total' },
			{ name: 'Connectivity', value: 'Requires phone for translation' },
		],
		image_url: 'https://images.unsplash.com/photo-1598331668826-20cecc596b86?w=800',
	},

	// ─── Speakers ─────────────────────────────────────────────────
	{
		name: 'Boom 360 Portable',
		type: 'physical' as const,
		price: 149.99,
		weight: 1.2,
		description: '360-degree portable Bluetooth speaker with deep bass radiator. 20-hour battery, IP67 dustproof and waterproof. Floats in water. PartySync mode links up to 100 speakers. Built-in USB-C power bank charges your phone.',
		categories: ['Volt Speakers'],
		custom_fields: [
			{ name: 'Output', value: '30W RMS' },
			{ name: 'Battery', value: '20 hours' },
			{ name: 'Water Resistance', value: 'IP67, floats' },
			{ name: 'Multi-speaker', value: 'PartySync (up to 100)' },
			{ name: 'Weight', value: '680g' },
		],
		image_url: 'https://images.unsplash.com/photo-1608043152269-423dbba4e7e1?w=800',
	},
	{
		name: 'Desk Speaker Pair',
		type: 'physical' as const,
		price: 199.99,
		weight: 3.0,
		description: 'Desktop stereo speakers with USB-C DAC built in — plug into your laptop for instant hi-fi. 4-inch woven Kevlar woofers and 1-inch silk dome tweeters. Bluetooth 5.3 for wireless, 3.5mm and optical inputs for versatility.',
		categories: ['Volt Speakers'],
		custom_fields: [
			{ name: 'Drivers', value: '4" Kevlar woofer + 1" silk tweeter per speaker' },
			{ name: 'Output', value: '50W RMS total' },
			{ name: 'Inputs', value: 'USB-C DAC, Bluetooth 5.3, 3.5mm, optical' },
			{ name: 'DAC', value: 'Built-in 24-bit/96kHz' },
			{ name: 'Weight', value: '1.4kg per speaker' },
		],
		image_url: 'https://images.unsplash.com/photo-1558618666-fcd25c85f82e?w=800',
	},
	{
		name: 'Campfire Mini',
		type: 'physical' as const,
		price: 59.99,
		weight: 0.4,
		description: 'Palm-sized outdoor speaker with a built-in carabiner clip. 12-hour battery, IP67 rated, and surprisingly loud for its size. Pairs two for stereo mode. The go-anywhere speaker for trails, hammocks, and campsites.',
		categories: ['Volt Speakers'],
		custom_fields: [
			{ name: 'Output', value: '10W' },
			{ name: 'Battery', value: '12 hours' },
			{ name: 'Water Resistance', value: 'IP67' },
			{ name: 'Size', value: '95mm diameter, palm-sized' },
			{ name: 'Stereo Pairing', value: 'Yes, pair two' },
		],
		image_url: 'https://images.unsplash.com/photo-1589003077984-894e133dabab?w=800',
	},

	// ─── Gaming ───────────────────────────────────────────────────
	{
		name: 'Warzone Pro Gaming Headset',
		type: 'physical' as const,
		price: 169.99,
		weight: 0.7,
		description: 'Competitive gaming headset with 50mm graphene drivers and 7.1 surround sound. Ultra-low 20ms wireless latency via 2.4GHz dongle. Detachable broadcast-quality boom mic with noise gate. 40-hour battery for marathon sessions.',
		categories: ['Volt Gaming'],
		custom_fields: [
			{ name: 'Drivers', value: '50mm graphene' },
			{ name: 'Surround', value: '7.1 virtual surround' },
			{ name: 'Latency', value: '20ms (2.4GHz dongle)' },
			{ name: 'Mic', value: 'Detachable boom, noise gate' },
			{ name: 'Battery', value: '40 hours' },
		],
		image_url: 'https://images.unsplash.com/photo-1618366712010-f4ae9c647dcb?w=800',
	},
	{
		name: 'Arena Wired Gaming',
		type: 'physical' as const,
		price: 79.99,
		weight: 0.5,
		description: 'Tournament-grade wired headset — zero latency, zero battery anxiety. 53mm drivers tuned for footstep detection. Compatible with PC, PlayStation, Xbox, and Switch via 3.5mm. Lightweight aluminum frame for all-day comfort.',
		categories: ['Volt Gaming'],
		custom_fields: [
			{ name: 'Drivers', value: '53mm neodymium' },
			{ name: 'Connection', value: '3.5mm wired (zero latency)' },
			{ name: 'Compatibility', value: 'PC, PS5, Xbox, Switch' },
			{ name: 'Frame', value: 'Aluminum, 230g' },
			{ name: 'Mic', value: 'Flip-to-mute boom' },
		],
		image_url: 'https://images.unsplash.com/photo-1612444530582-fc66f7e7ec5d?w=800',
	},
	{
		name: 'Stream Deck Mic',
		type: 'physical' as const,
		price: 119.99,
		weight: 0.8,
		description: 'USB condenser microphone for streaming and content creation. Cardioid pattern with real-time monitoring via 3.5mm headphone jack. Built-in pop filter, gain knob, and mute button. Zero-latency direct monitoring.',
		categories: ['Volt Gaming'],
		custom_fields: [
			{ name: 'Type', value: 'Condenser, cardioid' },
			{ name: 'Sample Rate', value: '24-bit/96kHz' },
			{ name: 'Connection', value: 'USB-C' },
			{ name: 'Monitoring', value: '3.5mm zero-latency' },
			{ name: 'Controls', value: 'Gain, mute, headphone volume' },
		],
		image_url: 'https://images.unsplash.com/photo-1598550476439-6847785fcea6?w=800',
	},
	{
		name: 'Gaming Earbuds Low-Lag',
		type: 'physical' as const,
		price: 69.99,
		weight: 0.12,
		description: 'True wireless gaming earbuds with 60ms latency mode. Dual-driver hybrid with dedicated bass unit. In-game/chat mix control via companion app. Works with mobile gaming, Switch, and PC via USB-C dongle.',
		categories: ['Volt Gaming'],
		custom_fields: [
			{ name: 'Latency', value: '60ms gaming mode' },
			{ name: 'Drivers', value: 'Dual hybrid (BA + dynamic)' },
			{ name: 'Battery', value: '6h buds / 24h total' },
			{ name: 'Dongle', value: 'USB-C included' },
			{ name: 'Mic', value: 'Beamforming dual mic' },
		],
		image_url: 'https://images.unsplash.com/photo-1590658165737-15a047b7c0a0?w=800',
	},
	{
		name: 'Haptic Bass Controller',
		type: 'physical' as const,
		price: 149.99,
		weight: 0.3,
		description: 'Wearable haptic bass device that clips to your collar or sits on your desk. Converts low-frequency audio into physical vibration you feel in your chest. Adds tactile bass to any headphone or earbud. Works with games, movies, and music.',
		categories: ['Volt Gaming'],
		custom_fields: [
			{ name: 'Type', value: 'Haptic bass transducer' },
			{ name: 'Frequency Range', value: '20Hz - 200Hz haptic' },
			{ name: 'Connection', value: 'Bluetooth 5.3 + 3.5mm passthrough' },
			{ name: 'Battery', value: '10 hours' },
			{ name: 'Intensity', value: '10 levels, app-controlled' },
		],
		image_url: 'https://images.unsplash.com/photo-1616588589676-62b3d4ff6e04?w=800',
	},
];
