// AUTO-GENERATED by scripts/analytics/derive-referrer-priors.mjs
// Source: data/sleepcountry-fingerprinted.jsonl (gitignored).
// Re-run after refreshing the fingerprinted data:
//   node scripts/analytics/fingerprint.mjs --output data/sleepcountry-fingerprinted.jsonl
//   node scripts/analytics/derive-referrer-priors.mjs
// See ADR-011 for the calibration verdict; cohorts with <30 labeled
// sessions emit null and the engine falls back to the default category prior.

import type { PersonaProbabilities } from './types';

export const SLEEPCOUNTRY_REFERRER_PRIORS: Record<string, PersonaProbabilities | null> = {
  internal: { researcher: 0.85, hunter: 0.04, gatherer: 0.09, gifter: 0.02 }, // labeled n=1109 (researcher=947 hunter=48 gatherer=96 gifter=18)
  direct: { researcher: 0.34, hunter: 0.25, gatherer: 0.41, gifter: 0.00 }, // labeled n=61 (researcher=21 hunter=15 gatherer=25 gifter=0)
  google: { researcher: 0.87, hunter: 0.00, gatherer: 0.13, gifter: 0.00 }, // labeled n=46 (researcher=40 hunter=0 gatherer=6 gifter=0)
  facebook: { researcher: 0.00, hunter: 0.99, gatherer: 0.00, gifter: 0.00 }, // labeled n=362 (researcher=1 hunter=360 gatherer=1 gifter=0)
  instagram: { researcher: 0.00, hunter: 1.00, gatherer: 0.00, gifter: 0.00 }, // labeled n=103 (researcher=0 hunter=103 gatherer=0 gifter=0)
  youtube: null, // labeled n=0 (researcher=0 hunter=0 gatherer=0 gifter=0), below min 30
  dormezvous: { researcher: 0.86, hunter: 0.03, gatherer: 0.10, gifter: 0.01 }, // labeled n=72 (researcher=62 hunter=2 gatherer=7 gifter=1)
  other: null, // labeled n=2 (researcher=1 hunter=0 gatherer=1 gifter=0), below min 30
};

/**
 * Bucket a raw referrer domain into one of the SLEEPCOUNTRY_REFERRER_PRIORS keys.
 * Mirrors scripts/analytics/fingerprint.mjs:bucketReferrer so priors line up with
 * the offline calibration. Empty / null / "(direct)" → "direct".
 */
export function bucketReferrer(domain: string | null | undefined): string {
  if (!domain || domain === '(direct)') return 'direct';
  const d = domain.toLowerCase();
  if (d.includes('facebook')) return 'facebook';
  if (d.includes('instagram')) return 'instagram';
  if (d.includes('google')) return 'google';
  if (d.includes('youtube')) return 'youtube';
  if (d.includes('dormezvous')) return 'dormezvous';
  if (d.includes('sleepcountry') || d === 'internal') return 'internal';
  return 'other';
}
