/**
 * Haven — Tailwind CSS Preset
 * Generated by brand-forge v2.0.0
 * DO NOT EDIT — regenerate with: brand-forge export tailwind
 */

/** @type {import("tailwindcss").Config} */
export default {
  theme: {
    extend: {
      colors: {
        primary: '#a3522d',
        secondary: '#8a4425',
        accent: '#2c6e63',
        neutral: {
          '50': '#faf9f7',
          '100': '#f5f3f0',
          '200': '#ebe8e3',
          '300': '#d9d4cc',
          '400': '#b5ada2',
          '500': '#8c8479',
          '600': '#6b6459',
          '700': '#4d473e',
          '800': '#353129',
          '900': '#231f1a',
          '950': '#141210',
        },
        success: '#2c6e63',
        warning: '#996d1a',
        error: '#b5403a',
        info: '#4a7fa5',
        surface: {
          'background': '#faf9f7',
          'foreground': '#231f1a',
          'card': '#ffffff',
          'card-foreground': '#353129',
          'muted': '#f5f3f0',
          'muted-foreground': '#6b6459',
          'border': '#ebe8e3',
        },
      },
      fontFamily: {
        display: ['DM Serif Display', 'Georgia', 'serif'],
        body: ['DM Sans', 'system-ui', 'sans-serif'],
        mono: ['JetBrains Mono', 'Menlo', 'monospace'],
      },
      fontSize: {
        'hero': ['3.5rem', { lineHeight: '1.05', fontWeight: '400' }],
        'h2': ['2.25rem', { lineHeight: '1.15', fontWeight: '400' }],
        'h3': ['1.5rem', { lineHeight: '1.25', fontWeight: '400' }],
        'h4': ['1.125rem', { lineHeight: '1.35', fontWeight: '600' }],
        'body-lg': ['1.125rem', { lineHeight: '1.65', fontWeight: '400' }],
        'body': ['1rem', { lineHeight: '1.6', fontWeight: '400' }],
        'body-sm': ['0.875rem', { lineHeight: '1.5', fontWeight: '400' }],
        'label': ['0.75rem', { lineHeight: '1.4', fontWeight: '500' }],
        'code': ['0.8125rem', { lineHeight: '1.5', fontWeight: '400' }],
      },
      spacing: {
        '1': '0.25rem',
        '2': '0.5rem',
        '3': '0.75rem',
        '4': '1rem',
        '6': '1.5rem',
        '8': '2rem',
        '12': '3rem',
        '16': '4rem',
        '24': '6rem',
      },
      borderRadius: {
        none: '0',
        'sm': '0.125rem',
        'md': '0.25rem',
        'lg': '0.375rem',
        'xl': '0.5rem',
        '2xl': '0.75rem',
        full: '9999px',
      },
      screens: {
        'sm': '640px',
        'md': '768px',
        'lg': '1024px',
        'xl': '1280px',
        '2xl': '1536px',
      },
      maxWidth: {
        content: '80rem',
      },
    },
  },
};